import Banner from "@/components/Banner";
import ContactForm from "@/components/ContactForm";
import Copyright from "@/components/Copyright";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import Services from "@/components/Services";
import Skills from "@/components/Skills";
import MyTestimonial from "@/components/Testmoial";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rakib Hossen - Full stack deeveloper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <header className="bg">
          <Navbar />
          <Banner />
        </header>
        <Services />
        <Skills />
        <Projects />
        <MyTestimonial />
        <ContactForm />
        <Copyright />
      </div>
    </>
  );
}
